version = 0.1

[default.deploy.parameters]
stack_name = "eduparent-demo"
region = "ap-northeast-1"
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-yaar5hnkkqcs"