AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: EduParent App Backend

Globals:
  Function:
    Timeout: 30
    MemorySize: 512
    Runtime: python3.11

Resources:
  EduParentAPI:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: apps/backend/
      Handler: lambda_handler.handler
      Policies:
        - AWSLambdaBasicExecutionRole
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - bedrock:InvokeModel
                - bedrock:InvokeModelWithResponseStream
                - bedrock:ListFoundationModels
                - bedrock:GetFoundationModel
              Resource:
                - !Sub "arn:aws:bedrock:${AWS::Region}::foundation-model/*"
                - !Sub "arn:aws:bedrock:${AWS::Region}:${AWS::AccountId}:*"
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
        RootEvent:
          Type: Api
          Properties:
            Path: /
            Method: ANY
      Environment:
        Variables:
          DATABASE_URL: "sqlite:///tmp/eduparent.db"
          JWT_SECRET_KEY: "your-jwt-secret-key-here"
          OPENAI_API_KEY: "your-openai-api-key-here"
          EVALUATION_MODEL: "openai:gpt-4o-mini"
          TEEN_RESPONSE_MODEL: "openai:gpt-4o-mini"
          MAX_ATTEMPTS: "3"
          PASS_THRESHOLD: "7"
          SCENARIOS_DIR: "app/roleplay/scenarios/data"

Outputs:
  ApiUrl:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
