name: eduparent-app

services:
  backend:
    build:
      context: ../apps/backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://eduparent:password@db:5432/eduparent
      - DEBUG=true
    env_file:
      - ../apps/backend/.env
    volumes:
      - ../apps/backend:/app
    depends_on:
      db:
        condition: service_healthy
    command: sh -c "uv run alembic upgrade head && uv run uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=eduparent
      - POSTGRES_USER=eduparent
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U eduparent -d eduparent"]
      interval: 5s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  postgres_data: